from dotenv import load_dotenv
import os

load_dotenv()

DOMAIN = os.getenv("DOMAIN")

# === DATABASE ===
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL and DATABASE_URL.startswith("postgresql://"):
    DATABASE_URL = DATABASE_URL.replace("postgresql", "postgresql+asyncpg", 1)
HERO_RENDER_BASE = os.getenv("HERO_RENDER_BASE")
INVENTORY_IMAGE_BASE = os.getenv("INVENTORY_IMAGE_BASE")

# === AUTH ===
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CLIENT_ID = os.getenv("TELEGRAM_CLIENT_ID")
TELEGRAM_CLIENT_SECRET = os.getenv("TELEGRAM_CLIENT_SECRET")
TELEGRAM_REDIRECT_URI = DOMAIN + os.getenv("TELEGRAM_REDIRECT_URI")

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24

# === PAYMENTS ===
MONOBANK_RAW_URL = os.getenv("MONOBANK_RAW_URL")
MONOBANK_TOKEN = os.getenv("MONOBANK_TOKEN")
MONOBANK_WEBHOOK_URL = DOMAIN + os.getenv("MONOBANK_WEBHOOK_URL")

CRYPTOCLOUD_API_KEY = os.getenv("CRYPTOCLOUD_API_KEY")
CRYPTOCLOUD_SHOP_ID = os.getenv("CRYPTOCLOUD_SHOP_ID")
CRYPTOCLOUD_SECRET_KEY = os.getenv("CRYPTOCLOUD_SECRET_KEY")

DISCORD_PAYMENT_INFO_WEBHOOK = os.getenv("DISCORD_PAYMENT_INFO_WEBHOOK")

# === APP INFO ===
APP_SECRET_VERSION = os.getenv("APP_SECRET_VERSION")
APP_SECRET_KEY = os.getenv("APP_SECRET_KEY")
APP_TOOLS_VERSION = os.getenv("APP_TOOLS_VERSION")